-keep class com.yourapp.obd.** { *; }
-keep class org.opencv.** { *; }
-keep class org.tensorflow.** { *; }
-keep class com.google.mediapipe.** { *; }
-keep class androidx.camera.** { *; }
-dontwarn org.opencv.**
-dontwarn org.tensorflow.**
-dontwarn com.google.mediapipe.**
-keepclassmembers class * extends androidx.room.RoomDatabase { *; }
-keep @dagger.hilt.android.HiltAndroidApp class *
-keep @dagger.hilt.android.AndroidEntryPoint class *
